#!/bin/sh
docker run --rm \
       --name minesweeperDB \
       -e POSTGRES_PASSWORD=Minesweeper321 \
       -e POSTGRES_USER=minesweeper \
       -e POSTGRES_DB=minesweeper\
       -d -p 5432:5432 \
       postgres:12.3-alpine
